from django.urls import path

from . import views
from . import views_admin


urlpatterns = [
    path("", views.home, name="home"),
    path("shop/", views.shop, name="shop"),
    path("mens-watches/", views.shop, {"gender": "men"}, name="mens-watches"),
    path("womens-watches/", views.shop, {"gender": "women"}, name="womens-watches"),
    path("luxury-watches/", views.shop, {"model": "luxury"}, name="luxury-watches"),
    path("about/", views.page, {"slug": "about"}, name="about"),
    path("contact/", views.page, {"slug": "contact"}, name="contact"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
    path("profile/", views.page, {"slug": "profile"}, name="profile"),
    path("orders/", views.page, {"slug": "orders"}, name="orders"),
    path("shop/<slug:slug>/", views.product_detail, name="product-detail"),
    path("cart/", views.cart_view, name="cart"),
    path("cart/add/<int:watch_id>/", views.cart_add, name="cart-add"),
    path("cart/update/<int:item_id>/", views.cart_update, name="cart-update"),
    path("cart/remove/<int:item_id>/", views.cart_remove, name="cart-remove"),
    path("cart/clear/", views.cart_clear, name="cart-clear"),
    path("cart/count/", views.cart_count, name="cart-count"),
    path("checkout/", views.cart_checkout, name="checkout"),
    path("checkout/complete/<int:order_id>/", views.order_confirmation, name="order-confirmation"),
    path("panel/dashboard/", views_admin.admin_dashboard, name="panel-dashboard"),
    path("panel/analytics/", views_admin.admin_analytics, name="panel-analytics"),
    path("panel/analytics/products/", views_admin.admin_analytics_products, name="panel-analytics-products"),
    path("panel/analytics/sales/", views_admin.admin_analytics_sales, name="panel-analytics-sales"),
    path("panel/analytics/visitors/", views_admin.admin_analytics_visitors, name="panel-analytics-visitors"),
    path("panel/products/", views_admin.admin_products, name="panel-products"),
    path("panel/products/add/", views_admin.admin_product_add, name="panel-product-add"),
    path("panel/products/search/", views_admin.admin_product_search, name="panel-product-search"),
    path("panel/ajax/add-brand/", views_admin.admin_add_brand, name="panel-add-brand"),
    path("panel/ajax/add-category/", views_admin.admin_add_category, name="panel-add-category"),
    path("panel/ajax/add-model/", views_admin.admin_add_model, name="panel-add-model"),
    path("panel/ajax/add-movement/", views_admin.admin_add_movement, name="panel-add-movement"),
    path("panel/ajax/add-strap-material/", views_admin.admin_add_strap_material, name="panel-add-strap-material"),
    path("panel/ajax/add-strap-color/", views_admin.admin_add_strap_color, name="panel-add-strap-color"),
    path("panel/products/<slug:slug>/toggle-featured/", views_admin.admin_product_toggle_featured, name="panel-product-toggle-featured"),
    path("panel/products/<slug:slug>/toggle-active/", views_admin.admin_product_toggle_active, name="panel-product-toggle-active"),
    path("panel/products/<slug:slug>/edit/", views_admin.admin_product_edit, name="panel-product-edit"),
    path("panel/products/<slug:slug>/delete/", views_admin.admin_product_delete, name="panel-product-delete"),
    path("panel/products/<slug:slug>/", views_admin.admin_product_detail, name="panel-product-detail"),
    path("panel/orders/", views_admin.admin_orders, name="panel-orders"),
    path("panel/cart/", views_admin.admin_cart, name="panel-cart"),
    path("panel/media/", views_admin.admin_media, name="panel-media"),
    path("panel/settings/", views_admin.admin_settings, name="panel-settings"),
]
