# Generated by Django 6.0.6 on 2026-06-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Homepage Hero', max_length=120)),
                ('video', models.FileField(upload_to='hero_videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Hero Video',
                'verbose_name_plural': 'Home Hero Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
