# Generated by Django 6.0.6 on 2026-06-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wshop', '0002_homehero'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
