# Generated by Django 6.0.6 on 2026-06-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wshop', '0003_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchimage',
            options={'ordering': ['-is_primary', '-is_main', 'created_at']},
        ),
        migrations.AddField(
            model_name='watchimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
