# Generated by Django 6.0.6 on 2026-06-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wshop', '0004_alter_watchimage_options_watchimage_is_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('cart_add', 'Cart Add'), ('checkout_start', 'Checkout Start'), ('order_placed', 'Order Placed')], db_index=True, max_length=30)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=512)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('watch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='wshop.watch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='wshop_analy_event_t_4d5913_idx'), models.Index(fields=['watch', '-created_at'], name='wshop_analy_watch_i_da6872_idx'), models.Index(fields=['session_key', '-created_at'], name='wshop_analy_session_c5a62a_idx')],
            },
        ),
    ]
