# Generated by Django 6.0.6 on 2026-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wshop', '0005_analyticsevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homehero',
            options={'ordering': ['-created_at'], 'verbose_name': 'Home Hero', 'verbose_name_plural': 'Home Heroes'},
        ),
        migrations.AddField(
            model_name='homehero',
            name='image',
            field=models.ImageField(blank=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='video',
            field=models.FileField(blank=True, upload_to='hero_videos/'),
        ),
    ]
