# Generated by Django 6.0.6 on 2026-07-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wshop', '0006_alter_homehero_options_homehero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='stock',
        ),
    ]
