# Generated by Django 6.0.6 on 2026-07-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wshop', '0008_remove_order_address_remove_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for cards and SEO.', max_length=300)),
                ('content', models.TextField(help_text='Full article body (HTML supported).')),
                ('image', models.ImageField(blank=True, upload_to='journals/')),
                ('category', models.CharField(choices=[('watch-guides', 'Watch Guides'), ('style', 'Style & Trends'), ('history', 'Watch History'), ('reviews', 'Reviews'), ('industry', 'Industry News'), ('lifestyle', 'Lifestyle')], default='style', max_length=30)),
                ('author', models.CharField(default='Wrist Hub Editorial', max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Article',
                'verbose_name_plural': 'Journal Articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
