# Generated by Django 6.0.6 on 2026-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wshop', '0010_gallerycategory_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
