# Generated by Django 6.0.6 on 2026-08-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wshop', '0013_productreview_reviewreply_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchimage',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Colour or finish shown in this image, e.g. Black or Rose Gold.', max_length=50),
        ),
    ]
